'use strict';
const $=id=>document.getElementById(id);
const TYPES={soldier:{name:'SQUAD',cost:40,desc:'8 soldiers · one shot each · 4% HQ damage'},tank:{name:'TANK',cost:50,desc:'Advance 2 · range 2 · explosive shell'},mg:{name:'MACHINE GUN',cost:40,desc:'10 bullets · assigned column'},holegun:{name:'HOLE GUN',cost:40,desc:'Fresh small hole · 2% HQ damage'},mortar:{name:'MORTAR',cost:200,desc:'10% HQ · nearby target · splash'}};
const MAXHP=100,MAXLEVEL=10,REROLL=2;
let view,s,drag=null,hover=null,aimStart=null,cardSignature='',last=0;
try{view=new HoleDrift3D($('game'));}catch(error){$('hint').textContent='3D could not start. Enable WebGL in your browser and reload.';throw error;}
const icons=Object.fromEntries(Object.keys(TYPES).map(k=>[k,view.icon(k)]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=a=>a[Math.floor(Math.random()*a.length)];
const count=p=>p.cols.reduce((a,b)=>a+b,0);
const GROWTH=[0,25,75,160,300,500,800,1200,1750,2500],UPGRADE_PRICES=[20,80,200,450,800,1300,2000,3000,4500];
// Main hole has ten levels; radius caps at one big cell.
const radius=level=>.28+.08*Math.max(0,Math.min(9,level-1));
function growthLevel(eaten,start=1){const total=GROWTH[start-1]+eaten;let level=1;while(level<MAXLEVEL&&total>=GROWTH[level])level++;return level;}
const upgradeCost=side=>UPGRADE_PRICES[s.upgrades[side]]??Infinity;
function resetHole(){const level=1+s.upgrades[s.side],r=radius(level);s.hole={x:4,z:s.side?r:10-r,r,level,eaten:0,vx:0,vz:0,contacts:new Set(),unitContacts:new Set()};s.bounces=0;}
function dims(u){return u.type==='soldier'?[.25,.5]:(u.type==='tank'||u.type==='holegun')?[.5,.5]:[1,1];}
function brickPos(p,i){return {x:p.x+(i%4)*.25+.125,z:p.z+Math.floor(i/4)*.5+.25};}
function seedBricks(){if(s.piles.some(count))return;s.piles=[];for(let z=2;z<8;z++)for(let x=0;x<8;x++){if(Math.random()>.65||s.units.some(u=>overlap(x+.5,z+.5,1,1,u.x,u.z,...dims(u))))continue;const layers=rand([1,2,2,3,4,5]);s.piles.push({id:s.nextId++,x,z,cols:Array(8).fill(layers)});}if(!s.piles.length)for(let z=2;z<8;z++)for(let x=0;x<8;x++)if(!s.units.some(u=>overlap(x+.5,z+.5,1,1,u.x,u.z,...dims(u)))){s.piles.push({id:s.nextId++,x,z,cols:Array(8).fill(2)});return;}}

function newMatch(){view.reset();s={phase:'aim',side:0,turn:1,time:0,bank:[0,0],hp:[MAXHP,MAXHP],upgrades:[0,0],units:[],piles:[],nextId:1,offers:[],selected:-1,angle:0,bounces:0,queue:[],holeShots:[],moves:[],tankMoves:[],impacts:[],timer:0,after:null,aiDelay:1,aiBuilds:0,placed:0,message:'',messageTime:0,totalCollected:[0,0]};seedBricks();resetHole();drag=null;hover=null;cardSignature='';$('ghost').hidden=true;updateUI();}
function overlap(ax,az,aw,ah,bx,bz,bw,bh){return Math.abs(ax-bx)<(aw+bw)/2-.001&&Math.abs(az-bz)<(ah+bh)/2-.001;}
function frontier(side){const own=s.units.filter(u=>u.side===side);return side?Math.min(10,Math.max(2,...own.map(u=>Math.floor(u.z)+1))):Math.max(0,Math.min(8,...own.map(u=>Math.floor(u.z))));}
function canPlace(x,z,type,side=s.side){if(!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x-.5-Math.round(x-.5))>.001||Math.abs(z-.5-Math.round(z-.5))>.001||x<.5||x>7.5||z<.5||z>9.5)return false;const row=Math.floor(z),col=Math.floor(x),edge=frontier(side);if(side?row>=edge:row<edge)return false;if(s.units.some(u=>Math.floor(u.x)===col&&Math.floor(u.z)===row))return false;return !s.piles.some(p=>p.x===col&&p.z===row&&count(p));}
function snap(p,type){return {x:Math.floor(p.x)+.5,z:Math.floor(p.z)+.5,type};}
function say(text){s.message=text;s.messageTime=2.5;}
function brickBurst(n,to=null){for(let i=0;i<n;i++){const a=i*2.399,r=.6+Math.random()*.5;view.effect({x:s.hole.x,z:s.hole.z,side:s.side},to||{x:s.hole.x+Math.cos(a)*r,z:s.hole.z+Math.sin(a)*r},'brick',.4+Math.random()*.4);}}
function spend(n,to=null){s.bank[s.side]-=n;brickBurst(n,to);}
function earn(n,side,pos,growth=false){if(!n)return;s.bank[side]+=n;s.totalCollected[side]+=n;if(growth){s.hole.eaten+=n;s.hole.level=growthLevel(s.hole.eaten,1+s.upgrades[side]);s.hole.r=radius(s.hole.level);}}
function collectColumn(p,i,side,growth=false){if(!p.cols[i])return 0;p.cols[i]--;p.offsets??=Array(8).fill(0);p.offsets[i]++;earn(1,side,brickPos(p,i),growth);return 1;}
function collectPile(p,n,side){let got=0;while(got<n&&count(p)){let max=0,index=-1;for(let i=0;i<8;i++)if(p.cols[i]>max){max=p.cols[i];index=i;}collectColumn(p,index,side);got++;}return got;}
function pointRectDist(x,z,x0,z0,x1,z1){const dx=Math.max(x0-x,0,x-x1),dz=Math.max(z0-z,0,z-z1);return dx*dx+dz*dz;}
function pointSegmentDist(x,z,ax,az,bx,bz){const dx=bx-ax,dz=bz-az,t=clamp(((x-ax)*dx+(z-az)*dz)/(dx*dx+dz*dz||1),0,1);return (x-ax-dx*t)**2+(z-az-dz*t)**2;}
// Exact swept circle / rectangle overlap: prevents frame-rate tunnelling and edge misses.
function sweptHit(ax,az,bx,bz,r,x0,z0,x1,z1){let lo=0,hi=1,dx=bx-ax,dz=bz-az;for(const [p,q]of [[-dx,ax-x0],[dx,x1-ax],[-dz,az-z0],[dz,z1-az]]){if(p===0){if(q<0){lo=2;break;}}else{const t=q/p;if(p<0)lo=Math.max(lo,t);else hi=Math.min(hi,t);}}if(lo<=hi&&lo<=1&&hi>=0)return true;let d=Math.min(pointRectDist(ax,az,x0,z0,x1,z1),pointRectDist(bx,bz,x0,z0,x1,z1));for(const [x,z]of [[x0,z0],[x0,z1],[x1,z0],[x1,z1]])d=Math.min(d,pointSegmentDist(x,z,ax,az,bx,bz));return d<=r*r;}
function holeCollect(h,ax,az,side,main=false){const active=new Set();for(const p of s.piles)for(let i=0;i<8;i++){if(!p.cols[i])continue;const k=p.id+':'+i,b=brickPos(p,i);if(sweptHit(ax,az,h.x,h.z,h.r*.9,b.x-.105,b.z-.22,b.x+.105,b.z+.22)&&!h.contacts.has(k)){collectColumn(p,i,side,main);h.contacts.add(k);if(!main){h.eaten++;h.r=Math.min(.5,h.r+.012);h.owner.fed=(h.owner.fed||0)+1;}}if(pointRectDist(h.x,h.z,b.x-.125,b.z-.25,b.x+.125,b.z+.25)<(h.r+.05)**2)active.add(k);}for(const k of h.contacts)if(!active.has(k))h.contacts.delete(k);for(const u of [...s.units]){if(u.side===side)continue;const [w,d]=dims(u),need=Math.max(w,d)/2;if(h.r+.001<need)continue;const reach=Math.max(.06,h.r-need+.12);if(pointSegmentDist(u.x,u.z,ax,az,h.x,h.z)<=reach*reach){s.units=s.units.filter(v=>v!==u);const n=u.type==='soldier'?TYPES.soldier.cost/16:TYPES[u.type].cost/2;earn(n,side,null,main);if(!main){h.eaten+=n;h.r=Math.min(.5,h.r+n*.012);h.owner.fed=(h.owner.fed||0)+n;}}}}
function collectDrift(ax,az){holeCollect(s.hole,ax,az,s.side,true);}
function damageWall(side,n){s.hp[side]=Math.max(0,s.hp[side]-n);if(!s.hp[side]){s.phase='over';s.queue=[];s.after=null;}}
function damageUnit(u,percent){u.hp-=u.type==='soldier'?u.maxhp:u.maxhp*percent/100;if(u.hp<=.00001)s.units=s.units.filter(v=>v!==u);}
function launch(angle=s.angle){if(s.phase!=='aim')return false;s.angle=clamp(angle,-1.25,1.25);s.phase='drift';s.hole.vx=Math.sin(s.angle)*5.8;s.hole.vz=(s.side?1:-1)*Math.cos(s.angle)*5.8;s.hole.contacts.clear();return true;}
function driftStep(dt){const h=s.hole,ax=h.x,az=h.z;h.x+=h.vx*dt;h.z+=h.vz*dt;let bounced=false;
 if(h.x<h.r){h.x=h.r;if(h.vx<0){h.vx=-h.vx;bounced=true;}}if(h.x>8-h.r){h.x=8-h.r;if(h.vx>0){h.vx=-h.vx;bounced=true;}}
 if(h.z<h.r){h.z=h.r;if(h.vz<0){h.vz=-h.vz;bounced=true;if(s.side===0)damageWall(1,5);}}if(h.z>10-h.r){h.z=10-h.r;if(h.vz>0){h.vz=-h.vz;bounced=true;if(s.side===1)damageWall(0,5);}}

 collectDrift(ax,az);if(bounced)s.bounces++;if(s.bounces>=5&&s.phase!=='over')finishDrift();
}
function offerCards(){s.offers=Object.keys(TYPES).sort(()=>Math.random()-.5).slice(0,3);s.selected=-1;}
function actionQueue(units,after){s.phase='actions';s.queue=[];s.timer=.15;s.after=after;const squads=new Set();for(const u of units){if(u.type==='soldier'){if(squads.has(u.squad))continue;squads.add(u.squad);}for(let i=0;i<(u.type==='mg'?10:1);i++)s.queue.push(()=>act(u));}if(!s.queue.length){s.after=null;after();}}
function enterBuild(){if(s.phase==='over')return;s.phase='build';offerCards();s.aiDelay=.7;s.aiBuilds=0;s.placed=0;s.aiRerolls=0;}
function finishDrift(){resetHole();actionQueue(s.units.filter(u=>u.side===s.side),enterBuild);}
function targetFor(u,range=30,includeBricks=true){const dir=u.side?1:-1,col=u.column??Math.floor(u.x);let best=null;for(const v of s.units){if(v.side===u.side||Math.floor(v.x)!==col)continue;const d=(v.z-u.z)*dir;if(d<-.01||d>range)continue;if(!best||d<best.d)best={kind:'unit',u:v,x:v.x,z:v.z,d};}if(includeBricks)for(const p of s.piles){if(p.x!==col||!count(p))continue;const d=(p.z+.5-u.z)*dir;if(d<-.01||d>range)continue;if(!best||d<best.d)best={kind:'bricks',p,x:p.x+.5,z:p.z+.5,d};}if(best)return best;const z=u.side?10:0;if(Math.abs(z-u.z)<=range)return {kind:'base',side:1-u.side,x:u.x,z,d:Math.abs(z-u.z)};return null;}
function harvest(p,side,mode){if(mode==='all'){for(let i=0;i<8;i++)while(p.cols[i])collectColumn(p,i,side);return;}let index=-1,best=-1;for(let i=0;i<8;i++)if(p.cols[i]>best&&p.cols[i]>0){best=p.cols[i];index=i;}if(index<0)return;if(mode==='top'){p.cols[index]--;earn(1,side);}else collectColumn(p,index,side);}
function blast(side,target,wallDamage=10,unitDamage=40){if(target.kind==='base')damageWall(target.side,wallDamage);else if(target.kind==='bricks')harvest(target.p,side,'all');else if(s.units.includes(target.u))damageUnit(target.u,unitDamage);for(const v of [...s.units])if(v.side!==side&&v.type==='soldier'&&Math.hypot(v.x-target.x,v.z-target.z)<=1)damageUnit(v,100);}
function bricksBlocked(x,z,w,d){return s.piles.some(p=>p.cols.some((n,i)=>{const b=brickPos(p,i);return n&&overlap(x,z,w,d,b.x,b.z,.25,.5);}));}
function squadTarget(units){const leader=units.reduce((a,b)=>a.side?(a.z>b.z?a:b):(a.z<b.z?a:b));return targetFor(leader,.85);}
function squadFire(units,target){for(const u of units){if(!s.units.includes(u))continue;let t=target;if(t.kind==='unit'&&!s.units.includes(t.u))t=targetFor(u,.85);if(!t)continue;shoot(u,t,4,5);}}
function advanceCrowds(dt){for(const m of [...s.moves]){const units=m.units.filter(u=>s.units.includes(u));if(!units.length){s.moves=s.moves.filter(v=>v!==m);continue;}const target=squadTarget(units);if(target){squadFire(units,target);s.moves=s.moves.filter(v=>v!==m);continue;}const step=Math.min(m.remaining,dt*1.1),dir=units[0].side?1:-1;let canMove=units.every(u=>u.z+dir*step>=.25&&u.z+dir*step<=9.75&&!bricksBlocked(u.x,u.z+dir*step,.22,.45));if(!canMove){const t=targetFor(units.reduce((a,b)=>dir>0?(a.z>b.z?a:b):(a.z<b.z?a:b)),1.2);if(t)squadFire(units,t);s.moves=s.moves.filter(v=>v!==m);continue;}for(const u of units)u.z+=dir*step;m.remaining-=step;if(m.remaining<=.0001){const t=squadTarget(units);if(t)squadFire(units,t);s.moves=s.moves.filter(v=>v!==m);}}}

function shoot(u,target,wallDamage,unitDamage,kind='shot'){if(!target)return;u.aim=Math.atan2(target.x-u.x,Math.abs(target.z-u.z));if(kind==='mortar'){view.effect(u,target,kind,1.3);s.impacts.push({left:1.3,side:u.side,target:{...target},wallDamage,unitDamage});return;}if(target.kind==='bricks'){const top=u.type==='mg';const height=top?Math.max(...target.p.cols)*.14:.1;view.effect(u,{...target,y:height},kind,.3);harvest(target.p,u.side,top?'top':u.type==='tank'?'all':'bottom');}else {view.effect(u,target,kind,.3);if(target.kind==='base')damageWall(target.side,wallDamage);else if(s.units.includes(target.u))damageUnit(target.u,unitDamage);}}
function act(u){if(!s.units.includes(u)||s.phase==='over')return;
 if(u.type==='soldier'){const units=s.units.filter(v=>v.type==='soldier'&&v.squad===u.squad);const target=squadTarget(units);if(target)squadFire(units,target);else s.moves.push({units,remaining:1});return;}
 if(u.type==='mg'){const t=targetFor(u);if(t)shoot(u,t,2,10);return;}
 if(u.type==='mortar'){const t=targetFor(u);if(t)shoot(u,t,10,40,'mortar');return;}
 if(u.type==='tank'){let t=targetFor(u,2);if(u.justBuilt){const nearest=targetFor(u);if(nearest?.kind==='bricks')t=nearest;}u.justBuilt=false;if(t)tankFire(u,t);else s.tankMoves.push({u,remaining:2});return;}
 if(u.type==='holegun'){s.holeShots.push({x:u.x,z:u.z,startZ:u.z,side:u.side,r:.125,owner:u,eaten:0,contacts:new Set()});}
}
function place(index,x,z){if(s.phase!=='build'||!s.offers[index])return false;const type=s.offers[index],cost=TYPES[type].cost;if(s.bank[s.side]<cost){say('Not enough bricks');return false;}if(!canPlace(x,z,type)){say('Choose an empty highlighted space');return false;}spend(cost,{x,z});s.placed++;const squad=s.nextId++,made=[];for(let i=0;i<(type==='soldier'?8:1);i++){const u={id:s.nextId++,squad,type,side:s.side,x:x+(type==='soldier'?(i%4)*.25-.375:0),z:z+(type==='soldier'?Math.floor(i/4)*.5-.25:0),hp:type==='soldier'?1:cost,maxhp:type==='soldier'?1:cost,built:s.time,fed:0,column:Math.floor(x),justBuilt:true};made.push(u);s.units.push(u);}s.offers[index]=rand(Object.keys(TYPES));s.selected=-1;hover=null;const offers=s.offers.slice();actionQueue(made,()=>{if(s.phase!=='over'){s.phase='build';s.offers=offers;s.aiDelay=.65;}});s.timer=.65;return true;}
function reroll(){if(s.phase!=='build'||s.bank[s.side]<REROLL)return false;spend(REROLL);offerCards();return true;}
function upgrade(){const cost=upgradeCost(s.side);if(s.phase!=='aim'||s.upgrades[s.side]>=MAXLEVEL-1||s.bank[s.side]<cost)return false;spend(cost);s.upgrades[s.side]++;resetHole();say('Starting hole upgraded to level '+s.hole.level);return true;}
function endTurn(){if(s.phase!=='build')return false;s.side=1-s.side;if(!s.side)s.turn++;s.phase='aim';s.selected=-1;hover=null;s.angle=0;seedBricks();resetHole();s.aiDelay=.9;return true;}
function ai(){if(s.side!==1)return;if(s.phase==='aim'){if(s.upgrades[1]<MAXLEVEL-1&&s.bank[1]>upgradeCost(1)+24)upgrade();let best=0,score=-1;for(let a=-1.1;a<=1.1;a+=.22){let val=0;for(const p of s.piles)val+=count(p)*Math.max(0,2-Math.abs(p.x+.5-(4+Math.tan(a)*(p.z+.5-s.hole.z))));if(val>score){score=val;best=a;}}launch(best);return;}if(s.phase==='build'){const options=[];for(let i=0;i<3;i++){const type=s.offers[i];if(TYPES[type].cost>s.bank[1])continue;for(let z=.5;z<10;z++)for(let x=.5;x<8;x++)if(canPlace(x,z,type,1))options.push({i,x,z,score:z*2+Math.random()*3+(type==='mortar'?2:0)});}if(options.length){options.sort((a,b)=>b.score-a.score);const o=options[0];s.aiBuilds++;place(o.i,o.x,o.z);}else if(!s.aiRerolls&&s.bank[1]>10){s.aiRerolls++;reroll();s.aiDelay=.6;}else endTurn();}}
function advanceHoleShots(dt){for(const h of [...s.holeShots]){const ax=h.x,az=h.z;h.z+=(h.side?1:-1)*2.5*dt;h.r=Math.min(.5,h.r+.09*dt);holeCollect(h,ax,az,h.side,false);if(h.z<=0||h.z>=10){damageWall(1-h.side,2);s.holeShots=s.holeShots.filter(v=>v!==h);}}}
function tankFire(u,t){shoot(u,t,20,40,'shell');for(const v of [...s.units])if(v.side!==u.side&&v.type==='soldier'&&Math.hypot(v.x-t.x,v.z-t.z)<=1)damageUnit(v,100);}
function advanceTanks(dt){for(const m of [...s.tankMoves]){const u=m.u;if(!s.units.includes(u)){s.tankMoves=s.tankMoves.filter(v=>v!==m);continue;}let target=targetFor(u,2);if(target){tankFire(u,target);s.tankMoves=s.tankMoves.filter(v=>v!==m);continue;}const distance=Math.min(m.remaining,.65*dt),nz=u.z+(u.side?1:-1)*distance;if(nz<.5||nz>9.5||bricksBlocked(u.x,nz,.5,.5)){s.tankMoves=s.tankMoves.filter(v=>v!==m);continue;}u.z=nz;m.remaining-=distance;target=targetFor(u,2);if(target)tankFire(u,target);if(target||m.remaining<=.0001)s.tankMoves=s.tankMoves.filter(v=>v!==m);}}
function tick(dt){s.time+=dt;if(s.phase!=='over'){advanceHoleShots(dt);advanceCrowds(dt);advanceTanks(dt);for(const hit of [...s.impacts]){hit.left-=dt;if(hit.left<=0){blast(hit.side,hit.target,hit.wallDamage,hit.unitDamage);s.impacts=s.impacts.filter(v=>v!==hit);}}}s.messageTime=Math.max(0,s.messageTime-dt);if(s.phase==='drift'){let left=dt;while(left>0&&s.phase==='drift'){const d=Math.min(.006,left);driftStep(d);left-=d;}}else if(s.phase==='actions'){s.timer-=dt;if(s.timer<=0&&!s.holeShots.length&&!s.moves.length&&!s.tankMoves.length&&!s.impacts.length){if(s.queue.length){s.queue.shift()();s.timer=.16;}else if(s.after){const after=s.after;s.after=null;after();}}}else if(s.side===1&&s.phase!=='over'){s.aiDelay-=dt;if(s.aiDelay<=0){s.aiDelay=.7;ai();}}}
function updateUI(){const mine=s.side===0,build=mine&&s.phase==='build',aim=mine&&s.phase==='aim';$('bank').textContent=s.bank[0];$('round').textContent='ROUND '+s.turn;for(const [side,n]of [[0,'player'],[1,'enemy']]){$(n+'HP').textContent=Math.ceil(s.hp[side])+'%';$(n+'Bar').style.width=s.hp[side]/MAXHP*100+'%';}$('phaseBadge').textContent=s.phase==='over'?'BATTLE OVER':(mine?'YOUR ':'ENEMY ')+(s.phase==='aim'||s.phase==='drift'?'DRIFT':s.phase==='actions'?'UNITS ACTING':'BUILD');$('holeInfo').textContent='HOLE LV. '+s.hole.level+(s.phase==='drift'?' · '+s.hole.eaten+' ▰':'');$('bounceInfo').textContent=s.phase==='drift'?Math.max(0,5-s.bounces)+' BOUNCES':(build?s.placed+' DEPLOYED':'START LV. '+(1+s.upgrades[0]));$('app').classList.toggle('building',build);$('app').classList.toggle('aiming',aim);$('buildPanel').hidden=!build;$('waiting').hidden=aim||build;$('waitingText').textContent=s.phase==='over'?'BATTLE COMPLETE':mine?'UNITS ACTING':s.phase==='drift'?'ENEMY DRIFTING':'ENEMY TURN';$('upgrade').hidden=!aim;$('upgrade').innerHTML=s.upgrades[0]>=MAXLEVEL-1?'MAX SIZE':'↑ SIZE <b>'+upgradeCost(0)+' ▰</b>';$('upgrade').disabled=s.bank[0]<upgradeCost(0)||s.upgrades[0]>=MAXLEVEL-1;$('hint').textContent=s.messageTime?s.message:aim?'Drag behind your wall · release to drift':build?(s.selected>=0?TYPES[s.offers[s.selected]].desc:'Drag a card to build · spend your bricks'):s.phase==='drift'?'Collect bricks · leave a pile to collect its next layer':s.phase==='over'?'Destroy the enemy HQ to win':'All units fire forward';$('reroll').disabled=s.bank[0]<REROLL;
 const sig=s.offers.join(',')+'|'+s.selected+'|'+s.bank[0]+'|'+s.placed;if(sig!==cardSignature){cardSignature=sig;$('cards').innerHTML=s.offers.map((k,i)=>'<button class="card '+(s.selected===i?'selected':'')+'" data-card="'+i+'" aria-label="'+TYPES[k].name+', '+TYPES[k].cost+' bricks. '+TYPES[k].desc+'" '+(s.bank[0]<TYPES[k].cost?'disabled':'')+'><img src="'+icons[k]+'" alt=""><span class="title">'+TYPES[k].name+'</span><span class="cost">'+TYPES[k].cost+' ▰</span></button>').join('');}
 $('outcome').hidden=s.phase!=='over';if(s.phase==='over'){$('outcomeTitle').textContent=s.hp[1]===0?'VICTORY!':'HQ DESTROYED';$('outcomeText').textContent=(s.hp[1]===0?'Enemy defenses have fallen.':'Your general will fight another day.')+' '+s.totalCollected[0]+' bricks collected.';}
}
$('game').addEventListener('pointerdown',e=>{if(s.side||s.phase!=='aim')return;const p=view.groundPoint(e.clientX,e.clientY);if(!p||p.z<10.35)return;aimStart={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);});
$('game').addEventListener('pointermove',e=>{if(aimStart)s.angle=clamp((e.clientX-aimStart.x)/115,-1.25,1.25);});
$('game').addEventListener('pointerup',()=>{if(aimStart){aimStart=null;launch();}});$('game').addEventListener('pointercancel',()=>aimStart=null);
$('game').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();s.angle=clamp(s.angle+(e.key==='ArrowLeft'?-.1:.1),-1.25,1.25);}if(e.key===' '||e.key==='Enter'){e.preventDefault();launch();}});
$('cards').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-card]');if(!b||b.disabled||s.phase!=='build')return;const i=+b.dataset.card;s.selected=i;drag={i,startX:e.clientX,startY:e.clientY,moved:false};});
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-card]');if(b&&!b.disabled)s.selected=+b.dataset.card;});
document.addEventListener('pointermove',e=>{if(!drag)return;drag.moved=drag.moved||Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>8;const type=s.offers[drag.i],p=view.groundPoint(e.clientX,e.clientY);if(p){hover=snap(p,type);hover.ok=canPlace(hover.x,hover.z,type);}if(drag.moved){$('ghost').hidden=false;$('ghost').textContent=TYPES[type].name;$('ghost').style.left=e.clientX+'px';$('ghost').style.top=e.clientY-16+'px';}});
document.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;$('ghost').hidden=true;if(d.moved&&hover&&hover.ok)place(d.i,hover.x,hover.z);hover=null;});document.addEventListener('pointercancel',()=>{drag=null;hover=null;$('ghost').hidden=true;});
$('game').addEventListener('pointerup',e=>{if(drag||s.side||s.phase!=='build'||s.selected<0)return;const p=view.groundPoint(e.clientX,e.clientY);if(p){const q=snap(p,s.offers[s.selected]);place(s.selected,q.x,q.z);}});
$('reroll').onclick=reroll;$('endTurn').onclick=endTurn;$('upgrade').onclick=upgrade;$('restart').onclick=newMatch;$('again').onclick=newMatch;$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
newMatch();function frame(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;tick(dt);updateUI();view.draw(s,dt,canPlace,hover);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.holeDrift={getState:()=>JSON.parse(JSON.stringify(s,(k,v)=>v instanceof Set?[...v]:v)),launch,place,reroll,upgrade,endTurn,restart:newMatch};
if(navigator.modelContext){for(const [name,description,fn,properties,required]of [['inspect_battle','Inspect Hole Drift state',()=>window.holeDrift.getState(),{},[]],['launch_hole','Launch hole at angle in radians',a=>launch(a.angle),{angle:{type:'number'}},['angle']],['place_unit','Place a card on a big-cell center',a=>place(a.card,a.x,a.z),{card:{type:'integer'},x:{type:'number'},z:{type:'number'}},['card','x','z']],['end_turn','End build phase',endTurn,{},[]]])try{navigator.modelContext.registerTool({name,description,inputSchema:{type:'object',properties,required},execute:async a=>({content:[{type:'text',text:JSON.stringify(fn(a))}]})});}catch{}}
